version: '3.8'

services:
  chatgpt-feedback:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - "dynamodb"
      - "dynamodb-test"
    links:
      - "dynamodb"
      - "dynamodb-test"
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      REGION: ${REGION}

  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"

  dynamodb-test:
    image: amazon/dynamodb-local
    container_name: dynamodb-test
    ports:
      - "8101:8000"
